config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  get 'welcome/index'
  get '/entries/new', to: redirect('/transaktions/new'), status: 200

  # Some controllers for JSON requests in support of interactivity:
  get '/entities/lookup', to: 'entities#lookup'
  get '/entities/latest', to: 'entities#latest'
  get '/accounts/lookup', to: 'accounts#lookup'
  get '/accounts/latest', to: 'accounts#latest'
  get '/items/lookup', to: 'items#lookup'
  get '/items/latest', to: 'items#latest'
  get '/gendescs/lookup', to: 'gendescs#lookup'
  get '/gendescs/latest', to: 'gendescs#latest'
  get '/units/lookup', to: 'units#lookup'
  get '/units/latest', to: 'units#latest'
  get '/items/account_for', to: "items#account_for"
  get '/accounts/starterpack', to: "accounts#starter_pack"
  post '/accounts/starterpack', to: "accounts#create_starter_pack"

  # Stuff to do after logging in:
  devise_for :users, :controllers => { :sessions => "sessions" }

  resources :entries
  resources :accounts
  resources :items
  resources :gendescs
  resources :units
  resources :transaktions
  resources :entities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :transaktion
  belongs_to :item, optional: true
  belongs_to :account
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
    # h/t Jaime Bellmyer http://stackoverflow.com/a/2140063
    session[:return_to] ||= request.referer
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        # h/t Jaime Bellmyer http://stackoverflow.com/a/2140063
        format.html { redirect_to session.delete(:return_to), notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:transaktion_id, :item_id, :price, :qty, :account_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(entry) do |f| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaktion_id %>
    <%= f.text_field :transaktion_id %>
  </div>

  <div class="field">
    <%= f.label :item_id %>
    <%= f.text_field :item_id %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :qty %>
    <%= f.text_field :qty %>
  </div>

  <div class="field">
    <%= f.label :account_id %>
    <%= f.text_field :account_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.haml
= form_for @entry do |f|
  %fieldset
    %legend edit entry
    - if @entry.item
      = autofill_inputs :entry, :item_id, "item", :value => @entry.item.id, :label => @entry.item.friendly_name
    -else
      = autofill_inputs :entry, :item_id, "item"
    = autofill_inputs :entry, :account_id, "account", :value => @entry.account.id, :label => @entry.account.friendly_name
    -#= label_and_input f, :price, "price", nil
    -#= label_and_input f, :qty, "quantity", nil
    = f.submit "save changes"

app/views/entries/index.html.haml
%table
  %caption journal
  %colgroup
    %col.date
    %col.desc
    %col.account
    %col.dr
    %col.cr
  %thead
    %tr
      %th date
      %th description
      %th account
      %th debit
      %th credit
  %tbody
    - current_user_id = user_signed_in? ? current_user.id : nil
    - ents = Entry.joins(:account).where("accounts.user_id" => current_user_id)
    -# by_transaktion = Entry.all.group_by {|entry| entry.transaktion}
    - by_transaktion = ents.group_by {|entry| entry.transaktion}
    - transaktions = by_transaktion.sort_by {|transaktion, entries| transaktion.date}
    - transaktions.each do |transaktion, entries|
      %tr.bold
        %td
          = link_to transaktion.date.strftime("%a %d %b %Y"), transaktion_path(transaktion)
        %td
          = link_to transaktion.entity.friendly_name, entity_path(transaktion.entity)
      - entries.each do |entry|
        - qty = entry.qty
        - amt = entry.price * qty
        %tr
          %td.amount
            = link_to "✎", edit_entry_path(entry) 
          %td 
            - if entry.item
              = link_to entry.item.friendly_name, item_path(entry.item)
              = qty != 1 ? " (qty #{qty})" : ""
          %td
            = link_to entry.account.friendly_name, account_path(entry.account)
          %td.amount
            = "%.2f" % amt if amt > 0
          %td.amount
            = "%.2f" % -amt if amt < 0

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaktion:</strong>
  <%= @entry.transaktion %>
</p>

<p>
  <strong>Item:</strong>
  <%= @entry.item %>
</p>

<p>
  <strong>Price:</strong>
  <%= @entry.price %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @entry.qty %>
</p>

<p>
  <strong>Account:</strong>
  <%= @entry.account %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Destroy',  entry, method: :delete %> |
<%= link_to 'Back', entries_path %>