config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  get 'welcome/index'
  get '/entries/new', to: redirect('/transaktions/new'), status: 200

  # Some controllers for JSON requests in support of interactivity:
  get '/entities/lookup', to: 'entities#lookup'
  get '/entities/latest', to: 'entities#latest'
  get '/accounts/lookup', to: 'accounts#lookup'
  get '/accounts/latest', to: 'accounts#latest'
  get '/items/lookup', to: 'items#lookup'
  get '/items/latest', to: 'items#latest'
  get '/gendescs/lookup', to: 'gendescs#lookup'
  get '/gendescs/latest', to: 'gendescs#latest'
  get '/units/lookup', to: 'units#lookup'
  get '/units/latest', to: 'units#latest'
  get '/items/account_for', to: "items#account_for"
  get '/accounts/starterpack', to: "accounts#starter_pack"
  post '/accounts/starterpack', to: "accounts#create_starter_pack"

  # Stuff to do after logging in:
  devise_for :users, :controllers => { :sessions => "sessions" }

  resources :entries
  resources :accounts
  resources :items
  resources :gendescs
  resources :units
  resources :transaktions
  resources :entities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
end

app/models/transaktion.rb
class Transaktion < ApplicationRecord
  belongs_to :entity

  # Magnitude is defined (WLOG) as your choice of sum of credit entries or
  # sum of debit entries
  def magnitude
    Entry.where(transaktion_id: self.id, qty: -1).sum :price
  end

end

app/controllers/transaktions_controller.rb
class TransaktionsController < ApplicationController
  before_action :set_transaktion, only: [:show, :edit, :update, :destroy]

  # GET /transaktions
  # GET /transaktions.json
  def index
    @transaktions = Transaktion.where(user_id: current_user_id)
  end

  # GET /transaktions/1
  # GET /transaktions/1.json
  def show
  end

  # GET /transaktions/new
  def new
    @transaktion = Transaktion.new
  end

  # GET /transaktions/1/edit
  def edit
  end

  # POST /transaktions
  # POST /transaktions.json
  def create
    @transaktion = Transaktion.new(transaktion_params)

    respond_to do |format|
      if valid_transaktion? and @transaktion.save
        @transaktion.user_id = current_user_id
        transaktion_id = @transaktion.id
        params["entry"].each_pair do |key|
          entry_params = params["entry"][key]
          entry_params[:transaktion_id] = transaktion_id
          # TODO make sure item_id is not a required field in model
          if key.to_i % 2 == 1 # odd key, credit entry_params
            entry_params["qty"] = -1
          end
          entry_params.permit!
          entry = Entry.new(entry_params)
        end
        format.html { redirect_to @transaktion, notice: 'Transaktion was successfully created.' }
        format.json { render :show, status: :created, location: @transaktion }
      else
        format.html { render :new }
        format.json { render json: @transaktion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transaktions/1
  # PATCH/PUT /transaktions/1.json
  def update
    respond_to do |format|
      if @transaktion.update(transaktion_params)
        format.html { redirect_to @transaktion, notice: 'Transaktion was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaktion }
      else
        format.html { render :edit }
        format.json { render json: @transaktion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transaktions/1
  # DELETE /transaktions/1.json
  def destroy
    @transaktion.destroy
    respond_to do |format|
      format.html { redirect_to transaktions_url, notice: 'Transaktion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaktion
      @transaktion = Transaktion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaktion_params
      params.require(:transaktion).permit(:date, :entity_id, :is_void)
    end

    def valid_transaktion?
      #TODO:
      # make sure all accounts referenced are accessible to user
      # make sure the transaktion entries balance
      # make sure data and entity fields are filled in

      # for now:
      true
    end

end

app/helpers/transaktions_helper.rb
module TransaktionsHelper
end

app/views/transaktions/_form.html.erb
<%= form_for(transaktion) do |f| %>
  <% if transaktion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaktion.errors.count, "error") %> prohibited this transaktion from being saved:</h2>

      <ul>
      <% transaktion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :entity_id %>
    <%= f.text_field :entity_id %>
  </div>

  <div class="field">
    <%= f.label :is_void %>
    <%= f.check_box :is_void %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transaktions/edit.html.haml
= form_for @transaktion do |f|
  %fieldset
    %legend edit transaction
    = label_and_input f, :date, "transaction date", nil
    = autofill_inputs :transaktion, :entity_id, "other party to transaction", :value => @transaktion.entity.id, :label => @transaktion.entity.friendly_name
    = f.submit "save changes"

app/views/transaktions/index.html.haml
%p#notice
  = notice

%table
  %caption your transactions
  %thead
  %tbody
    - @transaktions.each do |transaktion|
      %tr
        %td
          = link_to "✎", edit_transaktion_path(transaktion) 
        %td
          = link_to transaktion.date.strftime("%a %d %b %Y"), transaktion_path(transaktion)
        %td
          = link_to transaktion.entity.friendly_name, entity_path(transaktion.entity)
        %td.amount
          = "%.2f" % transaktion.magnitude

app/views/transaktions/new.html.haml
= form_for @transaktion do |f|
  %fieldset
    %legend point of sale information
    = f.label :date, "date of transaction:"
    = f.text_field :date, autocomplete: "off"
    = autofill_inputs :transaktion, :entity_id, "other party to transaction:"
  %fieldset.entry-block.credit
    %legend payments
    %table
      %thead
        %tr
          %th account
          %th amount
      %tbody
        = transaktion_entry 1, 1
    %button.replicator{:type => "button"} additional payment method
  %fieldset.entry-block.debit
    %legend purchases this transaction
    %table
      %thead
        %tr
          %th item
          %th account
          %th price
          %th quantity
          %th amount
      %tbody
        = transaktion_entry 0, 0
    %button.replicator{:type => "button"} additional item
  = f.submit "post transaction", id: "post"
  %fieldset
    %legend totals so far
    %label
      debits
      %input#debits.numeric{:disabled => true}
    %label
      credits
      %input#credits.numeric{:disabled => true}
    %label
      difference
      %input#difference.numeric{:disabled => true}

app/views/transaktions/show.html.haml
%p#notice
  =notice

%table
  %caption
    %span.entity-name
      - entity_id = @transaktion.entity_id
      %a{:href => entity_path(entity_id)}
        = Entity.find(entity_id).name
    %br
    %span.date
      - transaktion_date = @transaktion.date
      = transaktion_date.strftime "%A %d %B %Y"
  %colgroup
    %col
    %col
    %col
    %col
    %col
    %col
    %col
  %thead
    %tr
      %th account
      %th item
      %th price
      %th qty
      %th debit
      %th credit
      %th
  %tbody
    - current_user_id = user_signed_in? ? current_user.id : nil
    - if @transaktion.user_id == current_user_id
      - Entry.where(transaktion_id: @transaktion.id).each do |entry|
        - pq = entry.price * entry.qty
        - account_id = entry.account_id
        - item_id = entry.item_id
        %tr
          %td
            %a{:href => account_path(account_id)}
              = Account.find(account_id).friendly_name
          %td
            - if item_id
              %a{:href => item_path(item_id)}
                = Item.find(item_id).friendly_name
          %td.numeric
            = "%.4f" % entry.price if entry.qty > 0
          %td.numeric
            = "%.4f" % entry.qty if entry.qty > 0
          %td.numeric
            = "%.2f" % pq if pq > 0
          %td.numeric
            = "%.2f" % -pq if pq < 0
          %td
            = link_to "edit", edit_entry_path(entry)