config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  get 'welcome/index'
  get '/entries/new', to: redirect('/transaktions/new'), status: 200

  # Some controllers for JSON requests in support of interactivity:
  get '/entities/lookup', to: 'entities#lookup'
  get '/entities/latest', to: 'entities#latest'
  get '/accounts/lookup', to: 'accounts#lookup'
  get '/accounts/latest', to: 'accounts#latest'
  get '/items/lookup', to: 'items#lookup'
  get '/items/latest', to: 'items#latest'
  get '/gendescs/lookup', to: 'gendescs#lookup'
  get '/gendescs/latest', to: 'gendescs#latest'
  get '/units/lookup', to: 'units#lookup'
  get '/units/latest', to: 'units#latest'
  get '/items/account_for', to: "items#account_for"
  get '/accounts/starterpack', to: "accounts#starter_pack"
  post '/accounts/starterpack', to: "accounts#create_starter_pack"

  # Stuff to do after logging in:
  devise_for :users, :controllers => { :sessions => "sessions" }

  resources :entries
  resources :accounts
  resources :items
  resources :gendescs
  resources :units
  resources :transaktions
  resources :entities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
end

app/models/gendesc.rb
class Gendesc < ApplicationRecord
  has_many :item
end

app/controllers/gendescs_controller.rb
class GendescsController < ApplicationController
  before_action :set_gendesc, only: [:show, :edit, :update, :destroy]

  # GET /gendescs
  # GET /gendescs.json
  def index
    @gendescs = Gendesc.all
  end

  # GET /gendescs/1
  # GET /gendescs/1.json
  def show
  end

  # GET /gendescs/new
  def new
    @gendesc = Gendesc.new
  end

  # GET /gendescs/1/edit
  def edit
  end

  # POST /gendescs
  # POST /gendescs.json
  def create
    @gendesc = Gendesc.new(gendesc_params)

    respond_to do |format|
      if @gendesc.save
        Gendesc.update_friendly_names @gendesc
        format.html { redirect_to @gendesc, notice: 'Gendesc was successfully created.' }
        format.json { render :show, status: :created, location: @gendesc }
      else
        format.html { render :new }
        format.json { render json: @gendesc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gendescs/1
  # PATCH/PUT /gendescs/1.json
  def update
    respond_to do |format|
      if @gendesc.update(gendesc_params)
        format.html { redirect_to @gendesc, notice: 'Gendesc was successfully updated.' }
        format.json { render :show, status: :ok, location: @gendesc }
      else
        format.html { render :edit }
        format.json { render json: @gendesc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gendescs/1
  # DELETE /gendescs/1.json
  def destroy
    @gendesc.destroy
    respond_to do |format|
      format.html { redirect_to gendescs_url, notice: 'Gendesc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gendesc
      @gendesc = Gendesc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gendesc_params
      params.require(:gendesc).permit(:gendesc)
    end
end

app/helpers/gendescs_helper.rb
module GendescsHelper
end

app/views/gendescs/_form.html.erb
<%= form_for(gendesc) do |f| %>
  <% if gendesc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gendesc.errors.count, "error") %> prohibited this gendesc from being saved:</h2>

      <ul>
      <% gendesc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gendesc %>
    <%= f.text_field :gendesc %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gendescs/edit.html.haml
= form_for @gendesc do |f|
  %fieldset
    %legend change generic description
    = label_and_input f, :gendesc, "generic description", nil
    = f.submit "save changes"

app/views/gendescs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gendescs</h1>

<table>
  <thead>
    <tr>
      <th>Gendesc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gendescs.each do |gendesc| %>
      <tr>
        <td><%= gendesc.gendesc %></td>
        <td><%= link_to 'Show', gendesc %></td>
        <td><%= link_to 'Edit', edit_gendesc_path(gendesc) %></td>
        <td><%= link_to 'Destroy', gendesc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gendesc', new_gendesc_path %>

app/views/gendescs/new.html.haml
= form_for @gendesc do |f|
  %fieldset
    %legend generic description of product
    = label_and_input f, :gendesc, "generic description", nil, :autofocus => true
    = f.submit

app/views/gendescs/show.html.haml
%p#notice
  = notice

%table
  %caption
    = @gendesc.gendesc
  %thead
  %tbody
    - entries = Entry.joins(:item).where("items.gendesc_id": @gendesc.id)
    - entries.each do |entry|
      %tr
        %td
          = entry.transaktion.date.strftime "%a %d %b %y"
        %td
          - entity = entry.transaktion.entity
          = link_to entity.friendly_name, entity_path(entity)
        %td
          - item = entry.item
          = link_to entry.item.brand, item_path(item)
        %td
          %strong
            - unit_str = entry.item.unit.friendly_name.sub(/\(.*$/, "").strip.singularize
            = "#{"%.5f" % (entry.price/entry.item.size)} per #{entry.item.unit.short_form}"
          

%p possibly similar generic descriptors:
%ul
  - controller = GendescsController.new
  - words = @gendesc.friendly_name.downcase.split /[^a-z]+/
  - singulars = words.map {|word| word.singularize}
  - plurals = words.map {|word| word.pluralize}
  - words = singulars | plurals
  - others = Gendesc.friendly_names
  -# find subset of others having at least one of words as substring
  - others.select! do |other|
    - otherwords = other[:label].downcase.split /[^a-z]+/
    - singulars = otherwords.map {|word| word.singularize}
    - plurals = otherwords.map {|word| word.pluralize}
    - otherwords = singulars | plurals
    - other[:matches] = (words & otherwords).length
    - other[:matches] > 0
  - others.sort_by{|other| -other[:matches]}.each do |other|
    %li
      = link_to other[:label], gendesc_path(other[:value])